This is a simple example script to show you how to pull UniswapV2 summary information with one call

In [1]:
# import packages
import pandas as pd
import requests
from datetime import datetime

In [2]:
# make subgraph graphql call
url = 'https://api.thegraph.com/subgraphs/name/uniswap/uniswap-v2'

query = """
{
    uniswapDayDatas(first: 1000, orderBy: date, orderDirection: desc) {
        dailyVolumeETH
        dailyVolumeUSD
        dailyVolumeUntracked
        date
        totalLiquidityETH
        totalLiquidityUSD
        totalVolumeETH
        totalVolumeUSD
        txCount
    }
}"""
response = requests.post(url, json={'query': query})

In [3]:
# convert to dataframe
df = pd.json_normalize(response.json()['data']['uniswapDayDatas'])

In [8]:
# turn timestamp into datetime
df['date'] = pd.to_datetime(df['date'], unit='s')
df

,dailyVolumeETH,dailyVolumeUSD,dailyVolumeUntracked,date,totalLiquidityETH,totalLiquidityUSD,totalVolumeETH,totalVolumeUSD,txCount
0,64917.92423110550146433941188266977,250500847.0344626944655630680857928,350527732.4250229842012762387923821,2021-10-17,1188346.973700966216778879229787051,4509098504.312411802622405008943421,0,0,63403709
1,101149.3666951622782952849791765006,392010720.6977782401012671816041042,2450885138.922368502587102807098015,2021-10-16,1186585.10755212498095570880499545,4552109175.622836020658450746987295,0,0,63351991
2,146339.2356673442938071655872447538,557225332.0799495879645417385022766,953696555.5484774366935698798466348,2021-10-15,1180924.046449918835124589726309724,4556535676.106107331080852445950259,0,0,63269013
3,129351.0922253913417492189888019441,480935647.2958821363380924766742711,850123715.6141445234889976487669879,2021-10-14,1194603.227862003974853338498427062,4521526940.635145347108652664654946,0,0,63197461
4,127608.6473514312382726209016425812,446959813.3350347699039891468372209,944111575.704042657057211625974629,2021-10-13,1216311.494350274015360665152857417,4369564671.574278462813064261587573,0,0,63119552
...,...,...,...,...,...,...,...,...,...
524,0,0,0.198474744986308249812646943058877,2020-05-11,0.08877624195043786799999999999999999,18.75575726469834827925495451505825,0,0,21
525,0,0,0,2020-05-08,0.08871273859619242700000000000000001,18.81567240547130278983503413202888,0,0,18
526,0,0,0,2020-05-07,0.015921362843772577,3.205904320817102476152628363677479,0,0,10
527,0,0,0.00152961178082324924069982475906929,2020-05-06,0.015921362843758435,3.205901078245611864832838471153563,0,0,8
528,0,0,0.005465696446346381083685932486680732,2020-05-05,0.004908523513507407,0.9889999999999999999999999999999999,0,0,3

In [9]:
# download df as csv
df.to_csv('uniswapV2_daily_summary.csv', index=False)